[project]
name = "dashseo"
version = "0.0.3"
description = "A set of tools to make Dash SEO-friendly."
dependencies = [
    "dash",
    "markdown",
]
authors = [
  {name = "Elias Dabbas", email = "eliasdabbas@gmail.com"}
]